# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ${HOME}/.bash_profile ]; then
        . ${HOME}/.bash_profile
fi

# rvm-install added line:
if [[ -s /home/supo/.rvm/scripts/rvm ]] ; then source /home/supo/.rvm/scripts/rvm ; fi

