# environment variables
if [[ -s ${HOME}/.profile.d/environment ]] ; then source ${HOME}/.profile.d/environment ; fi

# rvm-install added line
if [[ -s ${HOME}/.rvm/scripts/rvm ]] ; then source ${HOME}/.rvm/scripts/rvm ; fi

rvm use 1.9.3

# customized autocompleters for bash
if [[ -s ${HOME}/.bash.d/autocompleter ]] ; then source ${HOME}/.bash.d/autocompleter ; fi

# tmux config
if [[ -s ${HOME}/.bash.d/tmux ]] ; then source ${HOME}/.bash.d/tmux ; fi

# git related completers
if [[ -s ${HOME}/.bash.d/git ]] ; then source ${HOME}/.bash.d/git ; fi
# merge .Xdefaults settings
#if [[ -s ${HOME}/.Xdefaults ]]; then xrdb -merge ${HOME}/.Xdefaults ; fi
