# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ${HOME}/.bash_profile ]; then
        . ${HOME}/.bash_profile
fi

if [[ -x ${HOME}/.profile_environment ]] ; then source ${HOME}/.profile_environment ; fi

# rvm-install added line:
if [[ -s ${HOME}/.rvm/scripts/rvm ]] ; then source ${HOME}/.rvm/scripts/rvm ; fi

