#!/usr/bin/env bash

"${HOME}/bin/update-status-bar"

# merge .Xdefaults settings
if [ -s "${HOME}/.Xdefaults" ]; then xrdb -merge "${HOME}/.Xdefaults" ; fi

# merge .Xmodmap settings
if [ -f "${HOME}/.Xmodmap" ]; then xmodmap "${HOME}/.Xmodmap"; fi

/run/current-system/sw/bin/feh --bg-scale "${HOME}/.wallpaper"

eval "$(gpg-agent \
  --daemon \
  --enable-ssh-support \
  --sh \
  --write-env-file ~/.gpg-agent)"

exec xmonad
