# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/hardware/network/broadcom-43xx.nix>
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "ohci_pci"
    "ehci_pci"
    "firewire_ohci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [
    "disable_mode=1"
    #"nomodeset"
    #"reboot=pci"
  ];
  boot.extraModulePackages = [ ];

  # keep generated fileSystems stuff from your install below is just structure.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/UUID0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."nixosroot".device = "/dev/disk/by-uuid/UUID1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/UUID2";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
}
